# Makefile — Java RMI Calculator
SHELL       := /bin/bash
JAVAC       := javac
JAVA        := java
RMIREG      := rmiregistry

OUT         := out
SRC         := $(wildcard *.java)

MAIN_SERVER := CalculatorServer
MAIN_CLIENT := CalculatorClient
SHARED_TEST := shared_test
PRIVATE_TEST:= per_client_test